export const VSM_OBJECTS = [
  'obj_base_gimmick',
  'obj_00_gimmick',
  'obj___gimmick',
  'obj_00_gimmick_old',
  'obj_aleph_gimmick',
  'obj_angelstar_gimmick',
  'obj_astellion_gimmick',
  'obj_convergence_gimmick',
  'obj_credits_gimmick_encore',
  'obj_credits_gimmick',
  'obj_distortedfate_gimmick',
  'obj_dracula_gimmick',
  'obj_firstbreath_gimmick',
  'obj_lastwish_gimmick',
  'obj_libertia_gimmick',
  'obj_marenol_gimmick',
  'obj_memories_gimmick',
  'obj_multigrode_gimmick',
  'obj_pictured_gimmick',
  'obj_plaude_gimmick',
  'obj_ram_gimmick',
  'obj_scarletdeath_gimmick',
  'obj_self_gimmick',
  'obj_stargazers_gimmick',
  'obj_stopmotion_gimmick',
  'obj_supernova_gimmick',
  'obj_times_gimmick',
  'obj_tutorial_gimmick',
  'obj_unraveling_gimmick',
  'obj_starcrashers_gimmick'
] as const

type vsm_objs = typeof VSM_OBJECTS[number]

export const VSM_MODS: Record<vsm_objs, { name: string; proxy?: 0 | -1 }[]> = {
  obj_base_gimmick: [
    { name: 'scrollspeed', proxy: -1 },
    { name: 'noterot', proxy: -1 },
    { name: 'velocity', proxy: -1 },
    { name: 'driven', proxy: -1 },
    { name: 'beat', proxy: -1 },
    { name: 'wave', proxy: -1 },
    { name: 'yoffset', proxy: -1 },
    { name: 'notealp', proxy: -1 },
    { name: 'scrollind0', proxy: -1 },
    { name: 'scrollind1', proxy: -1 },
    { name: 'scrollind2', proxy: -1 },
    { name: 'scrollind3', proxy: -1 },
    { name: 'scrollind4', proxy: -1 },
    { name: 'scrollind5', proxy: -1 },
    { name: 'scrollind6', proxy: -1 },
    { name: 'drawdist', proxy: -1 },
    { name: 'pburstleft', proxy: -1 },
    { name: 'pburstright', proxy: -1 },
    { name: 'particlexpower', proxy: -1 },
    { name: 'particleypower', proxy: -1 },
    { name: 'uialpha', proxy: -1 },
    { name: 'fx_contrast', proxy: -1 },
    { name: 'fx_glow', proxy: -1 },
    { name: 'fx_particleglow', proxy: -1 },
    { name: 'pburstspeed', proxy: -1 },
    { name: 'freeze', proxy: -1 },
    { name: 'fx_chroma_distort', proxy: -1 },
    { name: 'fx_film', proxy: -1 },
    { name: 'boost_distance', proxy: -1 },
    { name: 'boost_time', proxy: -1 },
    { name: 'hom', proxy: -1 },
    { name: 'enable_hue', proxy: -1 },
    { name: 'enable_posterize', proxy: -1 },

    { name: 'spinradius', proxy: 0 },
    { name: 'spiny', proxy: 0 },
    { name: 'spinx', proxy: 0 },
    { name: 'prx', proxy: 0 },
    { name: 'prxb', proxy: 0 },
    { name: 'prxc', proxy: 0 },
    { name: 'prxd', proxy: 0 },
    { name: 'pry', proxy: 0 },
    { name: 'pryb', proxy: 0 },
    { name: 'pryc', proxy: 0 },
    { name: 'pryd', proxy: 0 },
    { name: 'prsx', proxy: 0 },
    { name: 'pra', proxy: 0 },
    { name: 'przm', proxy: 0 },
    { name: 'przmb', proxy: 0 },
    { name: 'przmc', proxy: 0 },
    { name: 'przx', proxy: 0 },
    { name: 'przy', proxy: 0 },
    { name: 'prrx', proxy: 0 },
    { name: 'prry', proxy: 0 },
    { name: 'prrz', proxy: 0 },
    { name: 'prrzb', proxy: 0 },
    { name: 'shxs', proxy: 0 },
    { name: 'shxp', proxy: 0 },
    { name: 'shxa', proxy: 0 },
    { name: 'shys', proxy: 0 },
    { name: 'shyp', proxy: 0 },
    { name: 'shya', proxy: 0 },
    { name: 'prct', proxy: 0 },
    { name: 'prcb', proxy: 0 },
    { name: 'prcl', proxy: 0 },
    { name: 'prcr', proxy: 0 },
    { name: 'prvib', proxy: 0 },
    { name: 'shct', proxy: 0 },
    { name: 'shcb', proxy: 0 },
    { name: 'shcl', proxy: 0 },
    { name: 'shcr', proxy: 0 },
    { name: 'shfb', proxy: 0 },
    { name: 'shft', proxy: 0 },
    { name: 'shfl', proxy: 0 },
    { name: 'shfr', proxy: 0 }
  ],
  obj_00_gimmick: [],
  obj___gimmick: [
    { name: 'glitchamp' },
    { name: 'glitchoffset' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'bloom' },
    { name: 'gray' },
    { name: 'posx' },
    { name: 'posy' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'sina' },
    { name: 'sinp' },
    { name: 'sino' },
    { name: 'cosa' },
    { name: 'cosp' },
    { name: 'coso' },
    { name: 'tana' },
    { name: 'tanp' },
    { name: 'tano' },
    { name: 'static' },
    { name: 'uialpha' },
    { name: 'spinradiusx' },
    { name: 'spinradiusz' },
    { name: 'fakezy' },
    { name: 'fakezyb' },
    { name: 'float' },
    { name: 'wiggly' },
    { name: 'twx1' },
    { name: 'twy1' },
    { name: 'twa1' },
    { name: 'twr1' },
    { name: 'twx2' },
    { name: 'twy2' },
    { name: 'twa2' },
    { name: 'twr2' },
    { name: 'twx3' },
    { name: 'twy3' },
    { name: 'twa3' },
    { name: 'twr3' },
    { name: 'twx4' },
    { name: 'twy4' },
    { name: 'twa4' },
    { name: 'twr4' }
  ],
  obj_00_gimmick_old: [],
  obj_aleph_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'yoffset' }
  ],
  obj_angelstar_gimmick: [
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'wflash' },
    { name: 'rainbow' },
    { name: 'sides' },
    { name: 'notealp' },
    { name: 'video' },
    { name: 'noteoverlayalp' },
    { name: 'shadermode' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'gray' },
    { name: 'barrel' },
    { name: 'barrel2' },
    { name: 'hdistort' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'abx' },
    { name: 'aby' },
    { name: 'aberamp' },
    { name: 'glitchamp' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'fx_hue_hue' },
    { name: 'fx_hue_saturation' },
    { name: 'fx_edge' },
    { name: 'fx_posterize' },
    { name: 'fx_twirl' },
    { name: 'fx_posterize_vis' },
    { name: 'fx_underwater' },
    { name: 'bloom' },
    { name: 'angelstar_checker_alpha' },
    { name: 'angelstar_checker_set' },
    { name: 'fx_zoom' },
    { name: 'fx_red' }
  ],
  obj_astellion_gimmick: [
    { name: 'gray' },
    { name: 'barrel' },
    { name: 'barrel2' },
    { name: 'hdistort' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'abx' },
    { name: 'aby' },
    { name: 'aberamp' },
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'wflash' },
    { name: 'rainbow' },
    { name: 'sides' },
    { name: 'notealp' },
    { name: 'video' },
    { name: 'noteoverlayalp' },
    { name: 'astbars' },
    { name: 'bgalph' },
    { name: 'fxdist1' },
    { name: 'fxdist2' },
    { name: 'parttimer' }
  ],
  obj_convergence_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'supernova_dialogue' },
    { name: 'supernova_cg_xscale' },
    { name: 'supernova_cg_alpha' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'supernova_cg_frame' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg2_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'setup_co' }
  ],
  obj_credits_gimmick_encore: [],
  obj_credits_gimmick: [],
  obj_distortedfate_gimmick: [
    { name: 'df_sideline' },
    { name: 'df_whitebg' },
    { name: 'df_grid_alpha' },
    { name: 'df_grid_top' },
    { name: 'df_grid_bottom' },
    { name: 'df_sideline2' },
    { name: 'gray' },
    { name: 'barrel' },
    { name: 'barrel2' },
    { name: 'hdistort' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'abx' },
    { name: 'aby' },
    { name: 'aberamp' },
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'wflash' },
    { name: 'rainbow' },
    { name: 'sides' },
    { name: 'notealp' },
    { name: 'video' },
    { name: 'noteoverlayalp' },
    { name: 'df_countdown' },
    { name: 'lr_slash' },
    { name: 'lr_slash_color' },
    { name: 'lr_sides_blue' },
    { name: 'lr_sides_red' },
    { name: 'lr_sides_rev_blue' },
    { name: 'lr_sides_rev_red' },
    { name: 'lr_mountain_bg' }
  ],
  obj_dracula_gimmick: [
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'uialpha' },
    { name: 'vib' },
    { name: 'jart' },
    { name: 'jdesat' },
    { name: 'seedspeed' },
    { name: 'wflash' },
    { name: 'posx' },
    { name: 'posy' }
  ],
  obj_firstbreath_gimmick: [
    { name: 'df_sideline' },
    { name: 'df_whitebg' },
    { name: 'df_grid_alpha' },
    { name: 'df_grid_top' },
    { name: 'df_grid_bottom' },
    { name: 'df_sideline2' },
    { name: 'gray' },
    { name: 'barrel' },
    { name: 'barrel2' },
    { name: 'hdistort' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'abx' },
    { name: 'aby' },
    { name: 'aberamp' },
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'wflash' },
    { name: 'rainbow' },
    { name: 'sides' },
    { name: 'notealp' },
    { name: 'video' },
    { name: 'noteoverlayalp' },
    { name: 'df_countdown' },
    { name: 'lr_slash' },
    { name: 'lr_slash_color' },
    { name: 'lr_sides_blue' },
    { name: 'lr_sides_red' },
    { name: 'lr_sides_rev_blue' },
    { name: 'lr_sides_rev_red' },
    { name: 'lr_mountain_bg' },
    { name: 'setup_co' },
    { name: 'glitchamp' },
    { name: 'supernova_cg_alpha' },
    { name: 'supernova_cg_xscale' },
    { name: 'supernova_cg_frame' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' }
  ],
  obj_lastwish_gimmick: [
    { name: 'uialpha' },
    { name: 'bgalph' },
    { name: 'film' },
    { name: 'glow' },
    { name: 'filmsat' },
    { name: 'lwcover' },
    { name: 'lwflickerspd' },
    { name: 'lwjitterintensity' },
    { name: 'lwchroma' },
    { name: 'lwtext' }
  ],
  obj_libertia_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'supernova_dialogue' },
    { name: 'supernova_cg_xscale' },
    { name: 'supernova_cg_alpha' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' }
  ],
  obj_marenol_gimmick: [
    { name: 'glitchamp' },
    { name: 'glitchoffset' },
    { name: 'fish' },
    { name: 'posx' },
    { name: 'posy' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'sina' },
    { name: 'sinp' },
    { name: 'sino' },
    { name: 'cosa' },
    { name: 'cosp' },
    { name: 'coso' },
    { name: 'tana' },
    { name: 'tanp' },
    { name: 'tano' },
    { name: 'static' },
    { name: 'vibx' },
    { name: 'viby' },
    { name: 'uialpha' },
    { name: 'flicker' },
    { name: 'twx1' },
    { name: 'twy1' },
    { name: 'twa1' },
    { name: 'twr1' },
    { name: 'twx2' },
    { name: 'twy2' },
    { name: 'twa2' },
    { name: 'twr2' },
    { name: 'twx3' },
    { name: 'twy3' },
    { name: 'twa3' },
    { name: 'twr3' },
    { name: 'twx4' },
    { name: 'twy4' },
    { name: 'twa4' },
    { name: 'twr4' }
  ],
  obj_memories_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'supernova_dialogue' },
    { name: 'supernova_cg_xscale' },
    { name: 'supernova_cg_alpha' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'supernova_cg_frame' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'setup_co' }
  ],
  obj_multigrode_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'yoffset' },
    { name: 'dialogue_size' },
    { name: 'text_alpha' },
    { name: 'dialogue_id' },
    { name: 'fruitmemoryx' },
    { name: 'refreshdialogue' }
  ],
  obj_pictured_gimmick: [
    { name: 'c_flash' },
    { name: 'c_shader' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'holdoverlayalpha' },
    { name: '1_pinkbg_vis' },
    { name: '1_speech' },
    { name: '1_glitch' },
    { name: '2_boost' },
    { name: '2_dialbox_size' },
    { name: '2_dialbox_circles' },
    { name: '2_bg_pics' },
    { name: '2_dialbox_pulsar' },
    { name: '2_dialbox_speech' },
    { name: '2_bg_pinkbg_vis' },
    { name: '3_pinkbg_alph' },
    { name: '3_noteblack' },
    { name: '4_plusbg_vis' },
    { name: '4_plusbg_pulse' },
    { name: '4_square_alph' },
    { name: '4_square_rotspd' },
    { name: '4_square_scale' },
    { name: '5_video_toggle' },
    { name: '5_video_alph' },
    { name: '5_bord_alph' },
    { name: '5_abber' },
    { name: '6_glitch' },
    { name: '6_video_toggle' },
    { name: '6_video_alph' },
    { name: '6_red_layer_alph' },
    { name: '6_static_alph' },
    { name: '7_bg_vis' },
    { name: '7_note_vfx' },
    { name: '7_static_alph' }
  ],
  obj_plaude_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'supernova_dialogue' },
    { name: 'supernova_cg_xscale' },
    { name: 'supernova_cg_alpha' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'supernova_cg_frame' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'setup_co' },
    { name: 'setup_co_sect4' },
    { name: 'setup_co_sect6' },
    { name: 'setup_co_sect8' },
    { name: 'setup_co_sect12' },
    { name: 'setup_co_sect14' },
    { name: 'setup_co_end' },
    { name: 'plaudite_jacket' },
    { name: 'plaudite_sect2bg' },
    { name: 'plaudite_sect5bg' },
    { name: 'plaudite_sect7bg' },
    { name: 'unraveling_sidething' },
    { name: 'astellion_sidething' },
    { name: 'astellion_particles' },
    { name: 'supernova_bg_visible' },
    { name: 'libertia_bg_visible' },
    { name: 'stopmotion_bg_visible' },
    { name: 'convergence_bg_visible' },
    { name: 'plaudite_finaldropbg' },
    { name: 'plaudite_finaldropwhitebg' },
    { name: 'plaudite_slash_saturday' },
    { name: 'plaudite_slash_dawn' },
    { name: 'plaudite_ending_event' },
    { name: 'plaudite_red_particle' },
    { name: 'plaudite_pburst' },
    { name: 'plaudite_disable_jacket' },
    { name: 'plaudite_slash_neutral' },
    { name: 'plaudite_finaldropbg2' },
    { name: 'holdoverlayalpha' },
    { name: 'setup_co_sect1' },
    { name: 'hide_combo' }
  ],
  obj_ram_gimmick: [
    { name: 'glitchamp' },
    { name: 'glitchoffset' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'bloom' },
    { name: 'gray' },
    { name: 'posx' },
    { name: 'posy' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'sina' },
    { name: 'sinp' },
    { name: 'sino' },
    { name: 'cosa' },
    { name: 'cosp' },
    { name: 'coso' },
    { name: 'tana' },
    { name: 'tanp' },
    { name: 'tano' },
    { name: 'static' },
    { name: 'uialpha' },
    { name: 'spinradiusx' },
    { name: 'spinradiusz' },
    { name: 'fakezy' },
    { name: 'fakezyb' },
    { name: 'float' },
    { name: 'wiggly' },
    { name: 'planea' },
    { name: 'rotdir' },
    { name: 'texta' },
    { name: 'twx1' },
    { name: 'twy1' },
    { name: 'twa1' },
    { name: 'twr1' },
    { name: 'twx2' },
    { name: 'twy2' },
    { name: 'twa2' },
    { name: 'twr2' },
    { name: 'twx3' },
    { name: 'twy3' },
    { name: 'twa3' },
    { name: 'twr3' },
    { name: 'twx4' },
    { name: 'twy4' },
    { name: 'twa4' },
    { name: 'twr4' }
  ],
  obj_scarletdeath_gimmick: [
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'wflash' },
    { name: 'rainbow' },
    { name: 'sides' },
    { name: 'notealp' },
    { name: 'video' },
    { name: 'noteoverlayalp' },
    { name: 'shadermode' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'gray' },
    { name: 'barrel' },
    { name: 'barrel2' },
    { name: 'hdistort' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'abx' },
    { name: 'aby' },
    { name: 'aberamp' },
    { name: 'glitchamp' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'fx_hue_hue' },
    { name: 'fx_hue_saturation' },
    { name: 'fx_edge' },
    { name: 'fx_posterize' },
    { name: 'fx_twirl' },
    { name: 'fx_posterize_vis' },
    { name: 'fx_underwater' },
    { name: 'bloom' },
    { name: 'angelstar_checker_alpha' },
    { name: 'angelstar_checker_set' },
    { name: 'fx_zoom' },
    { name: 'fx_red' },
    { name: 'heartattack1' },
    { name: 'heartattack2' },
    { name: 'heartattack3' },
    { name: 'heartattack4' },
    { name: 'heartattack5' },
    { name: 'heartattack6' }
  ],
  obj_self_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'holdoverlayalpha' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'yoffset' },
    { name: 'scrollind0' },
    { name: 'scrollind1' },
    { name: 'scrollind2' },
    { name: 'scrollind3' },
    { name: 'scrollind4' },
    { name: 'scrollind5' },
    { name: 'scrollind6' },
    { name: 'stopmotionnoteskin' },
    { name: 'storycheck1' },
    { name: 'storycheck2' },
    { name: 'sm_bg_enable' },
    { name: 'sm_bg_fade_alpha' },
    { name: 'temporaryshadercreate' },
    { name: 'temporaryshaderdestroy' },
    { name: 'sm_leftbg_frameset' },
    { name: 'sm_rightbg_frameset' },
    { name: 'sm_pushcommand' },
    { name: 'sm_killcommand' },
    { name: 'sm_bar_show' },
    { name: 'sm_bar_progress' },
    { name: 'sm_cyclecount' },
    { name: 'self_satcolor' },
    { name: 'self_satalpha' },
    { name: 'self_satframe' },
    { name: 'self_tsukicolor' },
    { name: 'self_tsukialpha' },
    { name: 'self_tsukiframe' },
    { name: 'self_destsg' },
    { name: 'self_gravebg' },
    { name: 'self_gravefg' }
  ],
  obj_stargazers_gimmick: [
    { name: 'gray' },
    { name: 'barrel' },
    { name: 'barrel2' },
    { name: 'hdistort' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'abx' },
    { name: 'aby' },
    { name: 'aberamp' },
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'wflash' },
    { name: 'rainbow' },
    { name: 'sides' },
    { name: 'notealp' },
    { name: 'video' },
    { name: 'noteoverlayalp' },
    { name: 'bgalph' },
    { name: 'holdoverlayalpha' },
    { name: 'scorealph' },
    { name: 'sg_lanelines0' },
    { name: 'sg_lanelines1' },
    { name: 'sg_lanelines2' },
    { name: 'sg_judgeline' },
    { name: 'sg_starspawner' },
    { name: 'starspd_low' },
    { name: 'starspd_high' },
    { name: 'star_pause' },
    { name: 'starspawn' },
    { name: 'sg_endblip' },
    { name: 'sg_bg_alpha' },
    { name: 'sg_bg_speed' }
  ],
  obj_stopmotion_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'holdoverlayalpha' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'yoffset' },
    { name: 'scrollind0' },
    { name: 'scrollind1' },
    { name: 'scrollind2' },
    { name: 'scrollind3' },
    { name: 'scrollind4' },
    { name: 'scrollind5' },
    { name: 'scrollind6' },
    { name: 'stopmotionnoteskin' },
    { name: 'storycheck1' },
    { name: 'storycheck2' },
    { name: 'sm_bg_enable' },
    { name: 'sm_bg_fade_alpha' },
    { name: 'temporaryshadercreate' },
    { name: 'temporaryshaderdestroy' },
    { name: 'sm_leftbg_frameset' },
    { name: 'sm_rightbg_frameset' },
    { name: 'sm_pushcommand' },
    { name: 'sm_killcommand' },
    { name: 'sm_bar_show' },
    { name: 'sm_bar_progress' },
    { name: 'sm_cyclecount' }
  ],
  obj_supernova_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'supernova_dialogue' },
    { name: 'supernova_cg_xscale' },
    { name: 'supernova_cg_alpha' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'supernova_cg_frame' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'setup_co' },
    { name: 'setup_co_libertia' }
  ],
  obj_times_gimmick: [
    { name: 'glitchamp' },
    { name: 'static' },
    { name: 'wflash' },
    { name: 'tx' },
    { name: 'tx2' },
    { name: 'tx3' },
    { name: 'txj' },
    { name: 'ty' },
    { name: 'ty2' },
    { name: 'ty3' },
    { name: 'tyj' },
    { name: 'trz' },
    { name: 'trz2' },
    { name: 'tz' },
    { name: 'tzx' },
    { name: 'tzy' },
    { name: 'tspl' },
    { name: 'sepx' },
    { name: 'sepy' },
    { name: 'spinang' },
    { name: 'spinrad' },
    { name: 'siny' },
    { name: 'vib' },
    { name: 'hid1' },
    { name: 'hid2' },
    { name: 'hid3' },
    { name: 'hid4' },
    { name: 'hid5' }
  ],
  obj_tutorial_gimmick: [
    { name: 'glitchamp' },
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'scorealph' },
    { name: 'bgalph' },
    { name: 'noteoverlayalp' },
    { name: 'sg_endblip' },
    { name: 'glitchoffset' },
    { name: 'uhnoise' },
    { name: 'abberationxamp' },
    { name: 'abberationyamp' },
    { name: 'fish' },
    { name: 'static' },
    { name: 'sg_endblip_destroy' },
    { name: 'sn_bg_alpha' },
    { name: 'sn_bg_fxamp' },
    { name: 'sn_bg_animspd' },
    { name: 'yoffset' },
    { name: 'tutorialX' },
    { name: 'tutorialA' },
    { name: 'tutorialIndex' }
  ],
  obj_unraveling_gimmick: [
    { name: 'gray' },
    { name: 'barrel' },
    { name: 'barrel2' },
    { name: 'hdistort' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'abx' },
    { name: 'aby' },
    { name: 'aberamp' },
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'wflash' },
    { name: 'rainbow' },
    { name: 'sides' },
    { name: 'notealp' },
    { name: 'video' },
    { name: 'noteoverlayalp' }
  ],
  obj_starcrashers_gimmick: [
    { name: 'gray' },
    { name: 'barrel' },
    { name: 'barrel2' },
    { name: 'hdistort' },
    { name: 'fish' },
    { name: 'vig' },
    { name: 'abx' },
    { name: 'aby' },
    { name: 'aberamp' },
    { name: 'uialpha' },
    { name: 'cover1' },
    { name: 'cover2' },
    { name: 'cover3' },
    { name: 'wflash' },
    { name: 'rainbow' },
    { name: 'sides' },
    { name: 'notealp' },
    { name: 'video' },
    { name: 'noteoverlayalp' },
    { name: 'stargaze_mask_sat_alpha' },
    { name: 'stargaze_mask_tsuki_alpha' },
    { name: 'stargaze_mask_star_alpha' },
    { name: 'starspawner_timer' },
    { name: 'starspd_low' },
    { name: 'starspd_high' },
    { name: 'starspd_multiplier' },
    { name: 'spawn_star_mask' },
    { name: 'intro_gradient_alpha' },
    { name: 'missinglink_bg_alpha' },
    { name: 'turningpoint_bg_alpha' },
    { name: 'frostedmemories_bg_alpha' },
    { name: 'red_bg_alpha' },
    { name: 'black_bg_alpha' },
    { name: 'laser_spawn' },
    { name: 'spawn_centerrect_red' },
    { name: 'spawn_centerrect_black' },
    { name: 'lasthours_checker_alpha' },
    { name: 'lasthours_checker_chance' },
    { name: 'lasthours_checker_set' },
    { name: 'terminaljourney_bg_alpha' },
    { name: 'star_set_random_alpha' },
    { name: 'buildup_cutin_alpha' },
    { name: 'buildup_cutin_frame' },
    { name: 'chorus_town_alpha' },
    { name: 'chorus_backgroundchecker_alpha' },
    { name: 'chorus_firework' },
    { name: 'chorus_satalli_alpha' },
    { name: 'chorus_greenleft_overlay' },
    { name: 'chorus_satalli_bg_alpha' },
    { name: 'chorus_satalli_alli_particles' },
    { name: 'chorus_satalli_sat_particles' },
    { name: 'end_libertia_bg_alpha' },
    { name: 'whitefade_alpha' },
    { name: 'end_gravescene1_alpha' },
    { name: 'blackfade_alpha' },
    { name: 'end_gravescene2_alpha' },
    { name: 'ending_coroutine' }
  ]
}

export const VSM_EASING = [
  'linear',
  'inSine',
  'outSine',
  'inOutSine',
  'inQuad',
  'outQuad',
  'inOutQuad',
  'inCubic',
  'outCubic',
  'inOutCubic',
  'inQuart',
  'outQuart',
  'inOutQuart',
  'inQuint',
  'outQuint',
  'inOutQuint',
  'inExpo',
  'outExpo',
  'inOutExpo',
  'inCirc',
  'outCirc',
  'inOutCirc',
  'inBack',
  'outBack',
  'inOutBack',
  'inElastic',
  'outElastic',
  'inOutElastic',
  'inBounce',
  'outBounce',
  'inOutBounce'
]

/**
 *
 * @param v {string} The mod
 * @return {0|-1|1} the requirement: 1 for not-restricted, 0/-1 are restricted
 */
export function PROXY_REQUIREMENT(v: string): 0 | -1 | 1 {
  const base = VSM_MODS.obj_base_gimmick.find((mod) => mod.name == v)
  if (base) return base.proxy as 0 | -1
  return 1
}
