import { Invoke } from '@renderer/core/ipc'
import { External } from '@preload/external'
import { utils } from '@renderer/core/utils'

export const VSM_OBJECTS = [
  'obj_base_gimmick',
  'obj_00_gimmick',
  'obj___gimmick',
  'obj_00_gimmick_old',
  'obj_aleph_gimmick',
  'obj_angelstar_gimmick',
  'obj_astellion_gimmick',
  'obj_convergence_gimmick',
  'obj_credits_gimmick_encore',
  'obj_credits_gimmick',
  'obj_distortedfate_gimmick',
  'obj_dracula_gimmick',
  'obj_firstbreath_gimmick',
  'obj_lastwish_gimmick',
  'obj_libertia_gimmick',
  'obj_marenol_gimmick',
  'obj_memories_gimmick',
  'obj_multigrode_gimmick',
  'obj_pictured_gimmick',
  'obj_plaude_gimmick',
  'obj_ram_gimmick',
  'obj_scarletdeath_gimmick',
  'obj_self_gimmick',
  'obj_stargazers_gimmick',
  'obj_stopmotion_gimmick',
  'obj_supernova_gimmick',
  'obj_times_gimmick',
  'obj_tutorial_gimmick',
  'obj_unraveling_gimmick',
  'obj_starcrashers_gimmick'
] as const

type vsm_objs = (typeof VSM_OBJECTS)[number]

export const VSM_MODS: Record<vsm_objs, ({ name: string; proxy: 0 | -1 } | string)[]> = {
  obj_base_gimmick: [
    { name: 'scrollspeed', proxy: -1 },
    { name: 'noterot', proxy: -1 },
    { name: 'velocity', proxy: -1 },
    { name: 'driven', proxy: -1 },
    { name: 'beat', proxy: -1 },
    { name: 'wave', proxy: -1 },
    { name: 'yoffset', proxy: -1 },
    { name: 'notealp', proxy: -1 },
    { name: 'scrollind0', proxy: -1 },
    { name: 'scrollind1', proxy: -1 },
    { name: 'scrollind2', proxy: -1 },
    { name: 'scrollind3', proxy: -1 },
    { name: 'scrollind4', proxy: -1 },
    { name: 'scrollind5', proxy: -1 },
    { name: 'scrollind6', proxy: -1 },
    { name: 'drawdist', proxy: -1 },
    { name: 'pburstleft', proxy: -1 },
    { name: 'pburstright', proxy: -1 },
    { name: 'particlexpower', proxy: -1 },
    { name: 'particleypower', proxy: -1 },
    { name: 'uialpha', proxy: -1 },
    { name: 'fx_contrast', proxy: -1 },
    { name: 'fx_glow', proxy: -1 },
    { name: 'fx_particleglow', proxy: -1 },
    { name: 'pburstspeed', proxy: -1 },
    { name: 'freeze', proxy: -1 },
    { name: 'fx_chroma_distort', proxy: -1 },
    { name: 'fx_film', proxy: -1 },
    { name: 'boost_distance', proxy: -1 },
    { name: 'boost_time', proxy: -1 },
    { name: 'hom', proxy: -1 },
    { name: 'enable_hue', proxy: -1 },
    { name: 'enable_posterize', proxy: -1 },

    { name: 'spinradius', proxy: 0 },
    { name: 'spiny', proxy: 0 },
    { name: 'spinx', proxy: 0 },
    { name: 'prx', proxy: 0 },
    { name: 'prxb', proxy: 0 },
    { name: 'prxc', proxy: 0 },
    { name: 'prxd', proxy: 0 },
    { name: 'pry', proxy: 0 },
    { name: 'pryb', proxy: 0 },
    { name: 'pryc', proxy: 0 },
    { name: 'pryd', proxy: 0 },
    { name: 'prsx', proxy: 0 },
    { name: 'pra', proxy: 0 },
    { name: 'przm', proxy: 0 },
    { name: 'przmb', proxy: 0 },
    { name: 'przmc', proxy: 0 },
    { name: 'przx', proxy: 0 },
    { name: 'przy', proxy: 0 },
    { name: 'prrx', proxy: 0 },
    { name: 'prry', proxy: 0 },
    { name: 'prrz', proxy: 0 },
    { name: 'prrzb', proxy: 0 },
    { name: 'shxs', proxy: 0 },
    { name: 'shxp', proxy: 0 },
    { name: 'shxa', proxy: 0 },
    { name: 'shys', proxy: 0 },
    { name: 'shyp', proxy: 0 },
    { name: 'shya', proxy: 0 },
    { name: 'prct', proxy: 0 },
    { name: 'prcb', proxy: 0 },
    { name: 'prcl', proxy: 0 },
    { name: 'prcr', proxy: 0 },
    { name: 'prvib', proxy: 0 },
    { name: 'shct', proxy: 0 },
    { name: 'shcb', proxy: 0 },
    { name: 'shcl', proxy: 0 },
    { name: 'shcr', proxy: 0 },
    { name: 'shfb', proxy: 0 },
    { name: 'shft', proxy: 0 },
    { name: 'shfl', proxy: 0 },
    { name: 'shfr', proxy: 0 }
  ],
  obj_00_gimmick: [],
  obj___gimmick: [
    'glitchamp',
    'glitchoffset',
    'fish',
    'vig',
    'bloom',
    'gray',
    'posx',
    'posy',
    'cover1',
    'cover2',
    'cover3',
    'sina',
    'sinp',
    'sino',
    'cosa',
    'cosp',
    'coso',
    'tana',
    'tanp',
    'tano',
    'static',
    'uialpha',
    'spinradiusx',
    'spinradiusz',
    'fakezy',
    'fakezyb',
    'float',
    'wiggly',
    'twx1',
    'twy1',
    'twa1',
    'twr1',
    'twx2',
    'twy2',
    'twa2',
    'twr2',
    'twx3',
    'twy3',
    'twa3',
    'twr3',
    'twx4',
    'twy4',
    'twa4',
    'twr4'
  ],
  obj_00_gimmick_old: [],
  obj_aleph_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'yoffset'
  ],
  obj_angelstar_gimmick: [
    'uialpha',
    'cover1',
    'cover2',
    'cover3',
    'wflash',
    'rainbow',
    'sides',
    'notealp',
    'video',
    'noteoverlayalp',
    'shadermode',
    'scorealph',
    'bgalph',
    'gray',
    'barrel',
    'barrel2',
    'hdistort',
    'fish',
    'vig',
    'abx',
    'aby',
    'aberamp',
    'glitchamp',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'fx_hue_hue',
    'fx_hue_saturation',
    'fx_edge',
    'fx_posterize',
    'fx_twirl',
    'fx_posterize_vis',
    'fx_underwater',
    'bloom',
    'angelstar_checker_alpha',
    'angelstar_checker_set',
    'fx_zoom',
    'fx_red'
  ],
  obj_astellion_gimmick: [
    'gray',
    'barrel',
    'barrel2',
    'hdistort',
    'fish',
    'vig',
    'abx',
    'aby',
    'aberamp',
    'uialpha',
    'cover1',
    'cover2',
    'cover3',
    'wflash',
    'rainbow',
    'sides',
    'notealp',
    'video',
    'noteoverlayalp',
    'astbars',
    'bgalph',
    'fxdist1',
    'fxdist2',
    'parttimer'
  ],
  obj_convergence_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'supernova_dialogue',
    'supernova_cg_xscale',
    'supernova_cg_alpha',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'supernova_cg_frame',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg2_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'setup_co'
  ],
  obj_credits_gimmick_encore: [],
  obj_credits_gimmick: [],
  obj_distortedfate_gimmick: [
    'df_sideline',
    'df_whitebg',
    'df_grid_alpha',
    'df_grid_top',
    'df_grid_bottom',
    'df_sideline2',
    'gray',
    'barrel',
    'barrel2',
    'hdistort',
    'fish',
    'vig',
    'abx',
    'aby',
    'aberamp',
    'uialpha',
    'cover1',
    'cover2',
    'cover3',
    'wflash',
    'rainbow',
    'sides',
    'notealp',
    'video',
    'noteoverlayalp',
    'df_countdown',
    'lr_slash',
    'lr_slash_color',
    'lr_sides_blue',
    'lr_sides_red',
    'lr_sides_rev_blue',
    'lr_sides_rev_red',
    'lr_mountain_bg'
  ],
  obj_dracula_gimmick: [
    'cover1',
    'cover2',
    'cover3',
    'uialpha',
    'vib',
    'jart',
    'jdesat',
    'seedspeed',
    'wflash',
    'posx',
    'posy'
  ],
  obj_firstbreath_gimmick: [
    'df_sideline',
    'df_whitebg',
    'df_grid_alpha',
    'df_grid_top',
    'df_grid_bottom',
    'df_sideline2',
    'gray',
    'barrel',
    'barrel2',
    'hdistort',
    'fish',
    'vig',
    'abx',
    'aby',
    'aberamp',
    'uialpha',
    'cover1',
    'cover2',
    'cover3',
    'wflash',
    'rainbow',
    'sides',
    'notealp',
    'video',
    'noteoverlayalp',
    'df_countdown',
    'lr_slash',
    'lr_slash_color',
    'lr_sides_blue',
    'lr_sides_red',
    'lr_sides_rev_blue',
    'lr_sides_rev_red',
    'lr_mountain_bg',
    'setup_co',
    'glitchamp',
    'supernova_cg_alpha',
    'supernova_cg_xscale',
    'supernova_cg_frame',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd'
  ],
  obj_lastwish_gimmick: [
    'uialpha',
    'bgalph',
    'film',
    'glow',
    'filmsat',
    'lwcover',
    'lwflickerspd',
    'lwjitterintensity',
    'lwchroma',
    'lwtext'
  ],
  obj_libertia_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'supernova_dialogue',
    'supernova_cg_xscale',
    'supernova_cg_alpha',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static'
  ],
  obj_marenol_gimmick: [
    'glitchamp',
    'glitchoffset',
    'fish',
    'posx',
    'posy',
    'cover1',
    'cover2',
    'cover3',
    'sina',
    'sinp',
    'sino',
    'cosa',
    'cosp',
    'coso',
    'tana',
    'tanp',
    'tano',
    'static',
    'vibx',
    'viby',
    'uialpha',
    'flicker',
    'twx1',
    'twy1',
    'twa1',
    'twr1',
    'twx2',
    'twy2',
    'twa2',
    'twr2',
    'twx3',
    'twy3',
    'twa3',
    'twr3',
    'twx4',
    'twy4',
    'twa4',
    'twr4'
  ],
  obj_memories_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'supernova_dialogue',
    'supernova_cg_xscale',
    'supernova_cg_alpha',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'supernova_cg_frame',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'setup_co'
  ],
  obj_multigrode_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'yoffset',
    'dialogue_size',
    'text_alpha',
    'dialogue_id',
    'fruitmemoryx',
    'refreshdialogue'
  ],
  obj_pictured_gimmick: [
    'c_flash',
    'c_shader',
    'uialpha',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'holdoverlayalpha',
    '1_pinkbg_vis',
    '1_speech',
    '1_glitch',
    '2_boost',
    '2_dialbox_size',
    '2_dialbox_circles',
    '2_bg_pics',
    '2_dialbox_pulsar',
    '2_dialbox_speech',
    '2_bg_pinkbg_vis',
    '3_pinkbg_alph',
    '3_noteblack',
    '4_plusbg_vis',
    '4_plusbg_pulse',
    '4_square_alph',
    '4_square_rotspd',
    '4_square_scale',
    '5_video_toggle',
    '5_video_alph',
    '5_bord_alph',
    '5_abber',
    '6_glitch',
    '6_video_toggle',
    '6_video_alph',
    '6_red_layer_alph',
    '6_static_alph',
    '7_bg_vis',
    '7_note_vfx',
    '7_static_alph'
  ],
  obj_plaude_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'supernova_dialogue',
    'supernova_cg_xscale',
    'supernova_cg_alpha',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'supernova_cg_frame',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'setup_co',
    'setup_co_sect4',
    'setup_co_sect6',
    'setup_co_sect8',
    'setup_co_sect12',
    'setup_co_sect14',
    'setup_co_end',
    'plaudite_jacket',
    'plaudite_sect2bg',
    'plaudite_sect5bg',
    'plaudite_sect7bg',
    'unraveling_sidething',
    'astellion_sidething',
    'astellion_particles',
    'supernova_bg_visible',
    'libertia_bg_visible',
    'stopmotion_bg_visible',
    'convergence_bg_visible',
    'plaudite_finaldropbg',
    'plaudite_finaldropwhitebg',
    'plaudite_slash_saturday',
    'plaudite_slash_dawn',
    'plaudite_ending_event',
    'plaudite_red_particle',
    'plaudite_pburst',
    'plaudite_disable_jacket',
    'plaudite_slash_neutral',
    'plaudite_finaldropbg2',
    'holdoverlayalpha',
    'setup_co_sect1',
    'hide_combo'
  ],
  obj_ram_gimmick: [
    'glitchamp',
    'glitchoffset',
    'fish',
    'vig',
    'bloom',
    'gray',
    'posx',
    'posy',
    'cover1',
    'cover2',
    'cover3',
    'sina',
    'sinp',
    'sino',
    'cosa',
    'cosp',
    'coso',
    'tana',
    'tanp',
    'tano',
    'static',
    'uialpha',
    'spinradiusx',
    'spinradiusz',
    'fakezy',
    'fakezyb',
    'float',
    'wiggly',
    'planea',
    'rotdir',
    'texta',
    'twx1',
    'twy1',
    'twa1',
    'twr1',
    'twx2',
    'twy2',
    'twa2',
    'twr2',
    'twx3',
    'twy3',
    'twa3',
    'twr3',
    'twx4',
    'twy4',
    'twa4',
    'twr4'
  ],
  obj_scarletdeath_gimmick: [
    'uialpha',
    'cover1',
    'cover2',
    'cover3',
    'wflash',
    'rainbow',
    'sides',
    'notealp',
    'video',
    'noteoverlayalp',
    'shadermode',
    'scorealph',
    'bgalph',
    'gray',
    'barrel',
    'barrel2',
    'hdistort',
    'fish',
    'vig',
    'abx',
    'aby',
    'aberamp',
    'glitchamp',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'fx_hue_hue',
    'fx_hue_saturation',
    'fx_edge',
    'fx_posterize',
    'fx_twirl',
    'fx_posterize_vis',
    'fx_underwater',
    'bloom',
    'angelstar_checker_alpha',
    'angelstar_checker_set',
    'fx_zoom',
    'fx_red',
    'heartattack1',
    'heartattack2',
    'heartattack3',
    'heartattack4',
    'heartattack5',
    'heartattack6'
  ],
  obj_self_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'holdoverlayalpha',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'yoffset',
    'scrollind0',
    'scrollind1',
    'scrollind2',
    'scrollind3',
    'scrollind4',
    'scrollind5',
    'scrollind6',
    'stopmotionnoteskin',
    'storycheck1',
    'storycheck2',
    'sm_bg_enable',
    'sm_bg_fade_alpha',
    'temporaryshadercreate',
    'temporaryshaderdestroy',
    'sm_leftbg_frameset',
    'sm_rightbg_frameset',
    'sm_pushcommand',
    'sm_killcommand',
    'sm_bar_show',
    'sm_bar_progress',
    'sm_cyclecount',
    'self_satcolor',
    'self_satalpha',
    'self_satframe',
    'self_tsukicolor',
    'self_tsukialpha',
    'self_tsukiframe',
    'self_destsg',
    'self_gravebg',
    'self_gravefg'
  ],
  obj_stargazers_gimmick: [
    'gray',
    'barrel',
    'barrel2',
    'hdistort',
    'fish',
    'vig',
    'abx',
    'aby',
    'aberamp',
    'uialpha',
    'cover1',
    'cover2',
    'cover3',
    'wflash',
    'rainbow',
    'sides',
    'notealp',
    'video',
    'noteoverlayalp',
    'bgalph',
    'holdoverlayalpha',
    'scorealph',
    'sg_lanelines0',
    'sg_lanelines1',
    'sg_lanelines2',
    'sg_judgeline',
    'sg_starspawner',
    'starspd_low',
    'starspd_high',
    'star_pause',
    'starspawn',
    'sg_endblip',
    'sg_bg_alpha',
    'sg_bg_speed'
  ],
  obj_stopmotion_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'holdoverlayalpha',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'yoffset',
    'scrollind0',
    'scrollind1',
    'scrollind2',
    'scrollind3',
    'scrollind4',
    'scrollind5',
    'scrollind6',
    'stopmotionnoteskin',
    'storycheck1',
    'storycheck2',
    'sm_bg_enable',
    'sm_bg_fade_alpha',
    'temporaryshadercreate',
    'temporaryshaderdestroy',
    'sm_leftbg_frameset',
    'sm_rightbg_frameset',
    'sm_pushcommand',
    'sm_killcommand',
    'sm_bar_show',
    'sm_bar_progress',
    'sm_cyclecount'
  ],
  obj_supernova_gimmick: [
    'glitchamp',
    'uialpha',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'supernova_dialogue',
    'supernova_cg_xscale',
    'supernova_cg_alpha',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'supernova_cg_frame',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'setup_co',
    'setup_co_libertia'
  ],
  obj_times_gimmick: [
    'glitchamp',
    'static',
    'wflash',
    'tx',
    'tx2',
    'tx3',
    'txj',
    'ty',
    'ty2',
    'ty3',
    'tyj',
    'trz',
    'trz2',
    'tz',
    'tzx',
    'tzy',
    'tspl',
    'sepx',
    'sepy',
    'spinang',
    'spinrad',
    'siny',
    'vib',
    'hid1',
    'hid2',
    'hid3',
    'hid4',
    'hid5'
  ],
  obj_tutorial_gimmick: [
    'glitchamp',
    'uialpha',
    'cover1',
    'scorealph',
    'bgalph',
    'noteoverlayalp',
    'sg_endblip',
    'glitchoffset',
    'uhnoise',
    'abberationxamp',
    'abberationyamp',
    'fish',
    'static',
    'sg_endblip_destroy',
    'sn_bg_alpha',
    'sn_bg_fxamp',
    'sn_bg_animspd',
    'yoffset',
    'tutorialX',
    'tutorialA',
    'tutorialIndex'
  ],
  obj_unraveling_gimmick: [
    'gray',
    'barrel',
    'barrel2',
    'hdistort',
    'fish',
    'vig',
    'abx',
    'aby',
    'aberamp',
    'uialpha',
    'cover1',
    'cover2',
    'cover3',
    'wflash',
    'rainbow',
    'sides',
    'notealp',
    'video',
    'noteoverlayalp'
  ],
  obj_starcrashers_gimmick: [
    'gray',
    'barrel',
    'barrel2',
    'hdistort',
    'fish',
    'vig',
    'abx',
    'aby',
    'aberamp',
    'uialpha',
    'cover1',
    'cover2',
    'cover3',
    'wflash',
    'rainbow',
    'sides',
    'notealp',
    'video',
    'noteoverlayalp',
    'stargaze_mask_sat_alpha',
    'stargaze_mask_tsuki_alpha',
    'stargaze_mask_star_alpha',
    'starspawner_timer',
    'starspd_low',
    'starspd_high',
    'starspd_multiplier',
    'spawn_star_mask',
    'intro_gradient_alpha',
    'missinglink_bg_alpha',
    'turningpoint_bg_alpha',
    'frostedmemories_bg_alpha',
    'red_bg_alpha',
    'black_bg_alpha',
    'laser_spawn',
    'spawn_centerrect_red',
    'spawn_centerrect_black',
    'lasthours_checker_alpha',
    'lasthours_checker_chance',
    'lasthours_checker_set',
    'terminaljourney_bg_alpha',
    'star_set_random_alpha',
    'buildup_cutin_alpha',
    'buildup_cutin_frame',
    'chorus_town_alpha',
    'chorus_backgroundchecker_alpha',
    'chorus_firework',
    'chorus_satalli_alpha',
    'chorus_greenleft_overlay',
    'chorus_satalli_bg_alpha',
    'chorus_satalli_alli_particles',
    'chorus_satalli_sat_particles',
    'end_libertia_bg_alpha',
    'whitefade_alpha',
    'end_gravescene1_alpha',
    'blackfade_alpha',
    'end_gravescene2_alpha',
    'ending_coroutine'
  ]
}

export const VSM_EASING = [
  'linear',
  'inSine',
  'outSine',
  'inOutSine',
  'inQuad',
  'outQuad',
  'inOutQuad',
  'inCubic',
  'outCubic',
  'inOutCubic',
  'inQuart',
  'outQuart',
  'inOutQuart',
  'inQuint',
  'outQuint',
  'inOutQuint',
  'inExpo',
  'outExpo',
  'inOutExpo',
  'inCirc',
  'outCirc',
  'inOutCirc',
  'inBack',
  'outBack',
  'inOutBack',
  'inElastic',
  'outElastic',
  'inOutElastic',
  'inBounce',
  'outBounce',
  'inOutBounce'
]

/**
 *
 * @param v {string} The mod
 * @return {0|-1|1} the requirement: 1 for not-restricted, 0/-1 are restricted
 */
export function PROXY_REQUIREMENT(v: string): 0 | -1 | 1 {
  const base = VSM_MODS.obj_base_gimmick.find((mod) => typeof mod == 'object' && mod.name == v)
  if (base && typeof base == 'object') return base.proxy as 0 | -1
  return 1
}

export async function load_external_mods() {
  const r = await Invoke('read-external', { fname: 'vsm-objects.json' })
  if (!r) {
    console.log("Read External: vsm-objects failed")
    return
  }
  const mods = JSON.parse(r) as External.VSM_OBJECTS
  if (mods.VSM_EASING) {
    utils.clear_arr(VSM_EASING)
    VSM_EASING.push(...mods.VSM_EASING)
    console.log('Read External: VSM_EASING')
  }
  if (mods.VSM_OBJECTS) {
    // @ts-expect-error here VSM_OBJ should be immut but you know
    // this is external loading
    utils.clear_arr(VSM_OBJECTS)
    // @ts-expect-error not read-only (huh)
    VSM_OBJECTS.push(...mods.VSM_OBJECTS)
    console.log('Read External: VSM_OBJECTS')
  }
  if (mods.VSM_MODS) {
    for (const obj of utils.keyof(mods.VSM_MODS)) {
      if (VSM_MODS[obj]) {
        utils.clear_arr(VSM_MODS[obj])
        VSM_MODS[obj].push(...mods.VSM_MODS[obj])
      } else {
        VSM_MODS[obj] = mods.VSM_MODS[obj]
      }
    }
    console.log('Read External: VSM_MODS')
  }
}
