export const StartUpTips:string[] = [
  "also try vivid/otto!",
  "这么强？？？",
  "a-text: v-model=f**ker",
  "回滚到pre5——",
  "stray/vivify v2欢迎你！",
  "今天改了多少bug。不知道，多出来很多……",
  "早上是晚上的第二天，晚上是早上。",
  "A.R.K载体。可惜的是……",
  "今天回家！明天不回！",
  "npm run dev",
  "[vite] connection lost...",
  "[vue warn] Shit chart detected",
  "我草卡输入法了",
  "Felleta::stray-vivify",
  "int mian() {}",
  "#include <stray.h>",
  "No detours, no detours",
  "FPS: N/A",
  "chart.diff.fuck_shown()",
  "ultradash > J S > >",
  "卡 车 丢 失",
  "also try Rotaeno!"
]
